# MAIN
MAIN	= main.c
# end MAIN

# GET_SCREEN_SIZE
GET_SCREEN_SIZE	= get_screen_size.c
# end GET_SCREEN_SIZE

# INPUT_HANDLER
INPUT_HANDLER_DIR	= input_handler
INPUT_HANDLER	= $(addprefix ${INPUT_HANDLER_DIR}/, )
# end INPUT_HANDLER

# SIGNALS
SIGNALS_DIR	= signal_handler
SIGNALS		= $(addprefix ${SIGNALS_DIR}/, )
# end SIGNALS

# SRCS
SRCS		=\
${MAIN} ${GET_SCREEN_SIZE} ${INPUT_HANDLER} ${SIGNALS}
# end SRCS
