# MAIN
MAIN	= main.cpp
# end MAIN

# LOGGER
LOGGER_DIR = Logger
LOGGER = $(addprefix ${LOGGER_DIR}/, Logger.cpp loggerUtils.cpp)
# end LOGGER

# SERVER
SERVER	= Server.cpp
# end SERVER

# SRCS
SRCS		=\
${MAIN} ${LOGGER} #${SERVER}
# end SRCS
