version: "3"
networks:
    inception_net:
services:
    wordpress:
        depends_on:
            - mariadb
        networks:
            - inception_net
        env_file: .env
        build:
            context: ./wordpress
        ports:
            - '9000:9000'
        volumes:
            - wordpress_vol:/var/www/html
        restart: always
    nginx:
        networks:
            - inception_net
        build:
            context: ./nginx
        env_file:
            - .env
        ports:
            - '443:443'
        volumes:
            - wordpress_vol:/var/www/html
        restart: always
    redis:
        image: redis
        build:
            context: ./redis
        depends_on:
            - wordpress
        container_name: redis
        ports:
            - '6379:6379'
        networks:
            - inception_net
        restart: always
    mariadb:
        image: mariadb
        env_file: .env
        build:
            context: ./mariadb
            args:
              - WP_DB_NAME=${WP_DB_NAME}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_USER=${MYSQL_USER}
        container_name: mariadb
        ports:
            - '3306:3306'
        volumes:
            - mariadb_vol:/var/lib/mysql/
        networks:
            - inception_net
        restart: always
    ftp:
        image: ftp
        depends_on:
            - wordpress
        build:
            context: ./ftp
        container_name: ftp
        ports:
            - '21:21'
        volumes:
            - wordpress_vol:/home/tutsi
        networks:
            - inception_net
        restart: always
    adminer:
        image: adminer
        build:
            context: ./adminer
        depends_on:
            - wordpress
        container_name: adminer
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            - inception_net
        restart: always
    grafana:
        image: grafana
        ports:
            - '3000:3000'
            - '8086:8086'
        build:
            context: ./grafana
        container_name: grafana
        networks:
            - inception_net
        restart: always
    website:
        image: website
        build:
            context: ./website
        networks:
            - inception_net
        volumes:
            - wordpress_vol:/var/www/html
        restart: always


volumes:
    wordpress_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/tutsi/data/wordpress'
    mariadb_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/tutsi/data/mariadb'

