FROM debian:buster
RUN apt upgrade -y
RUN apt update -y


RUN apt install wget -y

RUN  apt install -y php php-fpm php-common php-json php-gd php-curl php-xml php-mysql php-imap php-cgi php-soap php-xmlrpc php-gettext php-ldap

COPY ./adminer.php ./adminer.php
#RUN cp -rf ./adminer.php /var/www/html/
#RUN chown -R www-data:www-data /var/www/html/adminer.php
#RUN chmod 755 /var/www/html/adminer.php
COPY ./setup.sh /setup.sh
CMD ["bash","./setup.sh"]

