# MAIN
MAIN	= main.cpp
# end MAIN

# LOGGER
LOGGER_DIR = logger
LOGGER = $(addprefix ${LOGGER_DIR}/, Log.cpp logUtils.cpp)
# end LOGGER

# SERVER
SERVER	= Server.cpp
# end SERVER

# SRCS
SRCS		=\
${MAIN} ${LOGGER} ${SERVER}
# end SRCS
